# Generated by Django 5.1.4 on 2024-12-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utakmice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utakmica",
            name="urlSlike",
            field=models.CharField(blank=True, max_length=2086, null=True),
        ),
    ]
