# Generated by Django 5.1.4 on 2024-12-16 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loginovanje", "0001_initial"),
        ("utakmice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipKarte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PreostaloKarata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preostalo", models.PositiveIntegerField()),
                (
                    "utakmica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utakmice.utakmica",
                    ),
                ),
                (
                    "tip_karte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="karte.tipkarte"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Karte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cena", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "kupac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="loginovanje.korisnik",
                    ),
                ),
                (
                    "tip_karte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="karte.tipkarte"
                    ),
                ),
            ],
        ),
    ]
