# Generated by Django 5.1.4 on 2025-01-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karte", "0005_remove_karte_cena_preostalokarata_cena"),
    ]

    operations = [
        migrations.AddField(
            model_name="karte",
            name="cena",
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="preostalokarata",
            name="cena",
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=7),
        ),
    ]
